from datetime import datetime, timezone
from enum import Enum
from typing import Optional, Dict, Any
from uuid import uuid4
from pydantic import BaseModel, Field


class ExecutionStatus(str, Enum):
    PENDING = "pending"
    APPROVED = "approved"
    REJECTED = "rejected"
    RUNNING = "running"
    DRY_RUN = "dry_run"
    SUCCESS = "success"
    FAILED = "failed"
    ROLLED_BACK = "rolled_back"
    FAILED_VERIFICATION = "failed_verification"
    ROLLBACK_FAILED = "rollback_failed"


class RollbackStatus(str, Enum):
    NOT_REQUIRED = "not_required"
    PENDING = "pending"
    SUCCESS = "success"
    FAILED = "failed"


class ActionType(str, Enum):
    """
    Actions allowed by the FinOps agent.
    """

    STOP_VM = "stop_vm"
    RESIZE_VM = "resize_vm"

    DELETE_DISK = "delete_disk"

    REMOVE_PUBLIC_IP = "remove_public_ip"

    ENABLE_AUTOSHUTDOWN = "enable_autoshutdown"

    APPLY_POLICY = "apply_policy"


class ExecutionRequest(BaseModel):
    """
    Generated by the AI recommendation layer.
    """

    action: ActionType

    resource_id: str

    parameters: Dict[str, Any] = {}

    reason: str = ""

    estimated_savings: float = 0

    baseline_monthly_cost: float | None = None

    expected_state: Dict[str, Any] = Field(
        default_factory=dict
    )

    # Collected from Azure/resource evidence before an operation.  This is
    # deliberately data, never an LLM-generated instruction.
    before_state: Dict[str, Any] = Field(default_factory=dict)

    risk_level: str = "low"

    confidence: float = 0

    requires_approval: bool = True

    dry_run: bool = True



class ExecutionResult(BaseModel):

    execution_id: str = Field(
        default_factory=lambda: str(uuid4())
    )

    action: ActionType

    resource_id: str

    status: ExecutionStatus

    message: str

    dry_run: bool = True

    baseline_monthly_cost: float | None = None

    expected_savings: float = 0.0

    previous_state: Optional[Dict[str, Any]] = None

    new_state: Optional[Dict[str, Any]] = None

    rollback_available: bool = False

    rollback: Dict[str, Any] = Field(default_factory=lambda: {
        "available": False,
        "strategy": None,
        "previous_sku": None,
        "rollback_required": False,
        "rollback_status": RollbackStatus.NOT_REQUIRED.value,
        "manual_intervention_required": False,
    })

    error: Optional[str] = None

    executed_at: datetime = Field(
        default_factory=lambda:
            datetime.now(timezone.utc)
    )
